#!/usr/bin/env python3
"""Gzip the portal page into a C header (deterministic: mtime=0, no name)."""
import gzip
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen_web_page.py <index.html> <out.h>", file=sys.stderr)
        return 2
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "rb") as f:
        raw = f.read()
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    lines = []
    for i in range(0, len(gz), 16):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in gz[i : i + 16]) + ",")
    body = "\n".join(lines)
    with open(dst, "w") as f:
        f.write(
            "// Generated by tools/gen_web_page.py from web/index.html -- do not edit.\n"
            f"// {len(raw)} bytes raw, {len(gz)} bytes gzipped.\n"
            "#ifndef WEB_PAGE_H\n#define WEB_PAGE_H\n\n"
            f"#define WEB_INDEX_GZ_LEN {len(gz)}u\n\n"
            "static const unsigned char web_index_gz[WEB_INDEX_GZ_LEN] = {\n"
            f"{body}\n}};\n\n#endif // WEB_PAGE_H\n"
        )
    print(f"web page: {len(raw)} -> {len(gz)} bytes gzipped")
    return 0


if __name__ == "__main__":
    sys.exit(main())
